import React from "react";
import { Link } from "react-router-dom";
import Arrow from "components/web/common/Arrow";
import routerPath from "etc/lib/path/routerPath";
import { useTranslation } from "react-i18next";

const Section05 = () => {
    const { t, i18n } = useTranslation();

    return (
        <>
            <div className="section05">
                <div className="sec_in">
                    <div className="title">
                        <h5>{t("main.sec05.subtitle")}</h5>
                        <div>
                            <h3>{t("main.sec05.title")}</h3>
                        </div>
                    </div>
                    <ul className="notice">
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner01.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner02.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner03.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner04.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner05.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner06.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner07.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner08.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner09.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner10.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner11.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner12.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner13.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner14.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner15.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner16.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner17.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner18.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner19.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner20.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner21.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner22.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li>
                            <Link>
                                <img
                                    src="/img/web/partner/partner23.png"
                                    alt=""
                                />
                            </Link>
                        </li>
                        <li></li>
                    </ul>
                </div>
            </div>
        </>
    );
};

export default Section05;
